# Virtual History Website Configuration

theme: jekyll-theme-feeling-responsive
plugins:
  - jekyll-feed
urlimg: "/images/"

markdown: kramdown

# For feeling-responsive
title: "Virtual History Title"
slogan: "Virtual History Slogan"
description: "About this site: Das Projekt Virtual History will am Beispiel des antiken Forum Romanum in Rom zeigen, wie eine digitale Aufbereitung aktueller Forschungsergebnisse im Medium VR völlig neue sinnlich-intellektuelle Erfahrungen ermöglicht."
logo: "logo.png"
favicon-32x32: "favicon-32x32.png"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
